# SPDX-FileCopyrightText: 2026 European Centre for Medium-Range Weather Forecasts (ECMWF)
# SPDX-License-Identifier: Apache-2.0

self-hosted-runner:
  labels:
    - platform-builder-docker-xl
    - platform-builder-Ubuntu-22.04
