[workspace]
resolver = "3"
members = [
    "crates/aviso",
    "crates/aviso-cli",
    "crates/aviso-py",
    "crates/finesse",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "Apache-2.0"
authors = [
    "Samet Demir <samet.demir@ecmwf.int>",
    "James Hawkes <james.hawkes@ecmwf.int>",
    "Tiago Quintino <tiago.quintino@ecmwf.int>",
]
repository = "https://github.com/ecmwf/aviso-client"
homepage = "https://github.com/ecmwf/aviso-client"
documentation = "https://github.com/ecmwf/aviso-client"

[workspace.dependencies]
anyhow = "1.0"
async-trait = "0.1"
base64 = "0.22"
clap = { version = "4.5", default-features = false, features = ["std", "derive", "help", "usage", "error-context"] }
proptest = "1.5"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "charset", "http2"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_norway = "0.9"
tempfile = "3.10"
thiserror = "2.0"
tokio = { version = "1.45", default-features = false, features = ["macros", "rt-multi-thread"] }
tracing = { version = "0.1", default-features = false, features = ["std", "attributes"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "json", "env-filter"] }
url = "2.5"
wiremock = "0.6"

[workspace.lints.rust]
missing_docs = "warn"
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
dbg_macro = "deny"
print_stdout = "deny"
print_stderr = "deny"
