# SPDX-FileCopyrightText: 2026 European Centre for Medium-Range Weather Forecasts (ECMWF)
# SPDX-License-Identifier: Apache-2.0

[toolchain]
channel = "1.95.0"
components = ["rustfmt", "clippy"]
profile = "minimal"
