#pragma once

/* Generated by cbindgen from crates/aviso-ffi. Do not edit by hand. Regenerate with `cargo run -p aviso-ffi --features gen-header --bin gen-header`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Discriminates an `AvisoError`.
 *
 * The first ten kinds mirror the core `ClientError`; the rest are conditions
 * the ABI itself reports: bad arguments, misuse, internal faults, a caught
 * Rust panic, and an unmapped (future) core variant. The discriminants are
 * fixed for ABI stability.
 */
typedef enum {
  /**
   * Network-level failure (connect, TLS, DNS, partial read).
   */
  AvisoErrorKind_Transport = 0,
  /**
   * Server returned a non-success HTTP status.
   */
  AvisoErrorKind_Http = 1,
  /**
   * Authentication setup or credential resolution failed.
   */
  AvisoErrorKind_Auth = 2,
  /**
   * A response body could not be decoded.
   */
  AvisoErrorKind_Decode = 3,
  /**
   * A `CloudEvent` envelope carried a malformed event id.
   */
  AvisoErrorKind_MalformedEvent = 4,
  /**
   * A gap was detected in a watch stream.
   */
  AvisoErrorKind_HistoryGap = 5,
  /**
   * A fatal wire-protocol condition was observed on a watch stream.
   */
  AvisoErrorKind_StreamProtocol = 6,
  /**
   * Configuration-time error (invalid source, missing field).
   */
  AvisoErrorKind_Config = 7,
  /**
   * A persistent state-store operation failed.
   */
  AvisoErrorKind_StateStore = 8,
  /**
   * A required trigger failed after all retries.
   */
  AvisoErrorKind_Trigger = 9,
  /**
   * An argument was null, not UTF-8, or otherwise malformed.
   */
  AvisoErrorKind_InvalidInput = 10,
  /**
   * The call was used incorrectly (for example, a blocking call from a
   * runtime or callback thread).
   */
  AvisoErrorKind_InvalidUsage = 11,
  /**
   * An internal invariant was violated.
   */
  AvisoErrorKind_Internal = 12,
  /**
   * A Rust panic was caught at the boundary.
   */
  AvisoErrorKind_Panic = 13,
  /**
   * An unmapped core error variant (the core enum grew).
   */
  AvisoErrorKind_Unknown = 14,
} AvisoErrorKind;

/**
 * Opaque client handle. Wraps the core client (cheap to clone, shares the
 * connection pool and auth state).
 */
typedef struct AvisoClient AvisoClient;

/**
 * Opaque client-builder handle. Setters mutate it in place; the first error
 * (a bad argument or an auth-construction failure) is remembered and surfaced
 * at `aviso_client_builder_build`.
 */
typedef struct AvisoClientBuilder AvisoClientBuilder;

/**
 * Result of a fallible C ABI call. Opaque to C; always freed with
 * `aviso_outcome_free`.
 */
typedef struct AvisoOutcome AvisoOutcome;

/**
 * C-visible error detail. The `const char*` fields borrow from the owning
 * `AvisoOutcome` and are valid until it is freed. A pointer
 * is null when the field does not apply (`request_id` when unknown,
 * `trigger_kind` / `error_kind` unless `kind` is `AvisoErrorKind_Trigger`).
 */
typedef struct {
  /**
   * The error kind.
   */
  AvisoErrorKind kind;
  /**
   * HTTP status when `kind` is `AvisoErrorKind_Http`, else `0`.
   */
  uint16_t http_status;
  /**
   * Human-readable message (never null). Credentials are never included;
   * server-supplied error text (such as an HTTP response body) may be.
   */
  const char *message;
  /**
   * Server-supplied request id, or null when unknown.
   */
  const char *request_id;
  /**
   * Trigger label when `kind` is `AvisoErrorKind_Trigger`, else null.
   */
  const char *trigger_kind;
  /**
   * Trigger inner-error label when applicable, else null.
   */
  const char *error_kind;
} AvisoError;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the library version as a static, NUL-terminated string. The pointer
 * is valid for the life of the process and must not be freed.
 */
const char *aviso_version(void);

/**
 * Creates a client builder for `base_url`. Returns a builder handle (null only
 * if an internal panic is trapped); a null or non-UTF-8 `base_url` is
 * remembered and reported at build time. Free an abandoned builder with
 * `aviso_client_builder_free`.
 *
 * # Safety
 *
 * `base_url`, when non-null, must point to a NUL-terminated C string.
 */
AvisoClientBuilder *aviso_client_builder_new(const char *base_url);

/**
 * Sets HTTP Basic credentials on the builder. A null or non-UTF-8 argument, or
 * a credential-construction failure, is remembered and reported at build time.
 *
 * # Safety
 *
 * `builder` must be a live builder handle from `aviso_client_builder_new`.
 * `username` and `password`, when non-null, must be NUL-terminated C strings.
 */
void aviso_client_builder_basic_auth(AvisoClientBuilder *builder,
                                     const char *username,
                                     const char *password);

/**
 * Builds the client, consuming the builder. On entry the builder is taken and
 * the caller's pointer is set to null (so a later free is a safe no-op), even
 * when the build fails. Returns an outcome carrying the client (retrieve it
 * with `aviso_outcome_take_client`) or a structured error.
 *
 * # Safety
 *
 * `builder` must point to a builder-handle pointer. `*builder`, when non-null,
 * must be a live handle from `aviso_client_builder_new`.
 */
AvisoOutcome *aviso_client_builder_build(AvisoClientBuilder **builder);

/**
 * Frees an abandoned client builder. Builders consumed by
 * `aviso_client_builder_build` are already freed; calling this on the
 * nulled-out pointer is a safe no-op.
 *
 * # Safety
 *
 * `builder`, when non-null, must be a live handle from
 * `aviso_client_builder_new` that was not consumed by a build.
 */
void aviso_client_builder_free(AvisoClientBuilder *builder);

/**
 * Frees a client. A null pointer is a no-op.
 *
 * # Safety
 *
 * `client`, when non-null, must be a live handle and not already freed.
 */
void aviso_client_free(AvisoClient *client);

/**
 * Fetches the schema catalog (`GET /api/v1/schema`) and returns it as a
 * compact-JSON string success value (retrieve it with
 * `aviso_outcome_take_string`), or a structured error.
 *
 * This call blocks. It must not be called from a thread already inside the
 * runtime (for example a watch or async callback); doing so returns an
 * `AvisoErrorKind_InvalidUsage` error.
 *
 * # Safety
 *
 * `client` must be a live handle from a successful build.
 */
AvisoOutcome *aviso_client_schema(const AvisoClient *client);

/**
 * Publishes a notification (`POST /api/v1/notification`) and returns the
 * server's response as a compact-JSON string success value (retrieve it with
 * `aviso_outcome_take_string`), or a structured error.
 *
 * `event_type` is required. `identifier_json`, when non-null, is a JSON object
 * of string-to-string identifier pairs; `payload_json`, when non-null, is any
 * JSON value. A null `identifier_json` or `payload_json` means the field is
 * omitted; a non-UTF-8 or otherwise malformed argument is an
 * `AvisoErrorKind_InvalidInput` error.
 *
 * This call blocks. It must not be called from a thread already inside the
 * runtime (for example a watch or async callback); doing so returns an
 * `AvisoErrorKind_InvalidUsage` error.
 *
 * # Safety
 *
 * `client` must be a live handle from a successful build. `event_type`,
 * `identifier_json`, and `payload_json`, when non-null, must be NUL-terminated
 * C strings.
 */
AvisoOutcome *aviso_client_notify(const AvisoClient *client,
                                  const char *event_type,
                                  const char *identifier_json,
                                  const char *payload_json);

/**
 * Fetches the schema for one event type (`GET /api/v1/schema/{event_type}`)
 * and returns it as a compact-JSON string success value (retrieve it with
 * `aviso_outcome_take_string`), or a structured error.
 *
 * This call blocks. It must not be called from a thread already inside the
 * runtime (for example a watch or async callback); doing so returns an
 * `AvisoErrorKind_InvalidUsage` error.
 *
 * # Safety
 *
 * `client` must be a live handle from a successful build. `event_type`, when
 * non-null, must be a NUL-terminated C string.
 */
AvisoOutcome *aviso_client_schema_for(const AvisoClient *client, const char *event_type);

/**
 * Wipes every notification for one stream (`DELETE
 * /api/v1/admin/wipe/stream`). Operator-only. Returns an empty success outcome
 * or a structured error.
 *
 * This call blocks. It must not be called from a thread already inside the
 * runtime (for example a watch or async callback); doing so returns an
 * `AvisoErrorKind_InvalidUsage` error.
 *
 * # Safety
 *
 * `client` must be a live handle from a successful build. `stream_name`, when
 * non-null, must be a NUL-terminated C string.
 */
AvisoOutcome *aviso_client_wipe_stream(const AvisoClient *client, const char *stream_name);

/**
 * Wipes every stream (`DELETE /api/v1/admin/wipe/all`). Operator-only. Returns
 * an empty success outcome or a structured error.
 *
 * This call blocks. It must not be called from a thread already inside the
 * runtime (for example a watch or async callback); doing so returns an
 * `AvisoErrorKind_InvalidUsage` error.
 *
 * # Safety
 *
 * `client` must be a live handle from a successful build.
 */
AvisoOutcome *aviso_client_wipe_all(const AvisoClient *client);

/**
 * Deletes a single notification by its `<event_type>@<sequence>` id (`DELETE
 * /api/v1/admin/notification/{id}`). Operator-only. Returns an empty success
 * outcome or a structured error.
 *
 * This call blocks. It must not be called from a thread already inside the
 * runtime (for example a watch or async callback); doing so returns an
 * `AvisoErrorKind_InvalidUsage` error.
 *
 * # Safety
 *
 * `client` must be a live handle from a successful build. `notification_id`,
 * when non-null, must be a NUL-terminated C string.
 */
AvisoOutcome *aviso_client_delete_notification(const AvisoClient *client,
                                               const char *notification_id);

/**
 * Returns `true` when the outcome carries no error.
 *
 * # Safety
 *
 * `outcome`, when non-null, must be a live pointer returned by this library
 * and not yet freed. A null pointer is tolerated and returns `false`.
 */
bool aviso_outcome_is_ok(const AvisoOutcome *outcome);

/**
 * Returns a borrowed pointer to the structured error, or null when the outcome
 * is a success. The pointer is valid until the outcome is freed.
 *
 * # Safety
 *
 * `outcome`, when non-null, must be a live pointer returned by this library
 * and not yet freed. A null pointer is tolerated and returns null.
 */
const AvisoError *aviso_outcome_error(const AvisoOutcome *outcome);

/**
 * Removes and returns the outcome's string success value, transferring
 * ownership to the caller, who must free it with `aviso_string_free`.
 * Returns null when the outcome holds no string (an error, an empty success,
 * or a value already taken).
 *
 * # Safety
 *
 * `outcome`, when non-null, must be a live pointer returned by this library
 * and not yet freed. A null pointer is tolerated and returns null.
 */
char *aviso_outcome_take_string(AvisoOutcome *outcome);

/**
 * Removes and returns the outcome's client success value, transferring
 * ownership to the caller, who must free it with `aviso_client_free`. Returns
 * null when the outcome holds no client.
 *
 * # Safety
 *
 * `outcome`, when non-null, must be a live pointer returned by this library
 * and not yet freed. A null pointer is tolerated and returns null.
 */
AvisoClient *aviso_outcome_take_client(AvisoOutcome *outcome);

/**
 * Frees an outcome. Any success value not taken out first is freed with it.
 * A null pointer is a no-op.
 *
 * # Safety
 *
 * `outcome` must be a pointer returned by this library and not already freed.
 */
void aviso_outcome_free(AvisoOutcome *outcome);

/**
 * Frees a string returned by an `..._take_string` accessor. A null pointer is
 * a no-op.
 *
 * # Safety
 *
 * `text` must be a pointer returned by this library's take-string accessors
 * and not already freed.
 */
void aviso_string_free(char *text);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
