#pragma once

/* Generated by cbindgen from crates/aviso-ffi. Do not edit by hand. Regenerate with `cargo run -p aviso-ffi --features gen-header --bin gen-header`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Discriminates an `AvisoError`.
 *
 * The first ten kinds mirror the core `ClientError`; the rest are conditions
 * the ABI itself reports: bad arguments, misuse, internal faults, a caught
 * Rust panic, and an unmapped (future) core variant. The discriminants are
 * fixed for ABI stability.
 */
typedef enum {
  /**
   * Network-level failure (connect, TLS, DNS, partial read).
   */
  AvisoErrorKind_Transport = 0,
  /**
   * Server returned a non-success HTTP status.
   */
  AvisoErrorKind_Http = 1,
  /**
   * Authentication setup or credential resolution failed.
   */
  AvisoErrorKind_Auth = 2,
  /**
   * A response body could not be decoded.
   */
  AvisoErrorKind_Decode = 3,
  /**
   * A `CloudEvent` envelope carried a malformed event id.
   */
  AvisoErrorKind_MalformedEvent = 4,
  /**
   * A gap was detected in a watch stream.
   */
  AvisoErrorKind_HistoryGap = 5,
  /**
   * A fatal wire-protocol condition was observed on a watch stream.
   */
  AvisoErrorKind_StreamProtocol = 6,
  /**
   * Configuration-time error (invalid source, missing field).
   */
  AvisoErrorKind_Config = 7,
  /**
   * A persistent state-store operation failed.
   */
  AvisoErrorKind_StateStore = 8,
  /**
   * A required trigger failed after all retries.
   */
  AvisoErrorKind_Trigger = 9,
  /**
   * An argument was null, not UTF-8, or otherwise malformed.
   */
  AvisoErrorKind_InvalidInput = 10,
  /**
   * The call was used incorrectly (for example, a blocking call from a
   * runtime or callback thread).
   */
  AvisoErrorKind_InvalidUsage = 11,
  /**
   * An internal invariant was violated.
   */
  AvisoErrorKind_Internal = 12,
  /**
   * A Rust panic was caught at the boundary.
   */
  AvisoErrorKind_Panic = 13,
  /**
   * An unmapped core error variant (the core enum grew).
   */
  AvisoErrorKind_Unknown = 14,
} AvisoErrorKind;

/**
 * HTTP method for the webhook trigger. Discriminants are fixed for ABI
 * stability and mirror the core `HttpMethod`.
 */
typedef enum {
  /**
   * `POST` (the webhook default).
   */
  AvisoHttpMethod_Post = 0,
  /**
   * `GET`.
   */
  AvisoHttpMethod_Get = 1,
  /**
   * `PUT`.
   */
  AvisoHttpMethod_Put = 2,
  /**
   * `PATCH`.
   */
  AvisoHttpMethod_Patch = 3,
  /**
   * `DELETE`.
   */
  AvisoHttpMethod_Delete = 4,
} AvisoHttpMethod;

/**
 * Opaque client handle. Wraps the core client (cheap to clone, shares the
 * HTTP connections and auth state).
 */
typedef struct AvisoClient AvisoClient;

/**
 * Opaque client-builder handle. Setters mutate it in place; the first error
 * (a bad argument or an auth-construction failure) is remembered and surfaced
 * at `aviso_client_builder_build`.
 */
typedef struct AvisoClientBuilder AvisoClientBuilder;

/**
 * A read-only view of one notification, valid only for the `on_notification`
 * call it is passed to. The `identifier` and `payload` are pre-serialized to
 * compact JSON; the accessors return borrowed pointers into this view.
 */
typedef struct AvisoNotification AvisoNotification;

/**
 * Result of a fallible C ABI call. Opaque to C; always freed with
 * `aviso_outcome_free`.
 */
typedef struct AvisoOutcome AvisoOutcome;

/**
 * Opaque trigger handle. Built by a factory, tuned by the setters, and
 * consumed by `aviso_watch_request_add_trigger` (which nulls the caller's
 * pointer) or freed with `aviso_trigger_free`.
 */
typedef struct AvisoTrigger AvisoTrigger;

/**
 * Opaque handle to a running watch. Stop it with `aviso_watch_stop`, block for
 * its completion with `aviso_watch_wait`, and release it with
 * `aviso_watch_free`.
 */
typedef struct AvisoWatch AvisoWatch;

/**
 * Opaque builder for a watch request. Setters mutate it in place; the first
 * bad argument is remembered and surfaced through `on_end` when the watch
 * starts. Consumed by `aviso_client_watch` (which nulls the caller's pointer)
 * or freed with `aviso_watch_request_free`.
 */
typedef struct AvisoWatchRequest AvisoWatchRequest;

/**
 * C-visible error detail. The `const char*` fields borrow from the owning
 * `AvisoOutcome` and are valid until it is freed. A pointer
 * is null when the field does not apply (`request_id` when unknown,
 * `trigger_kind` / `error_kind` unless `kind` is `AvisoErrorKind_Trigger`).
 */
typedef struct {
  /**
   * The error kind.
   */
  AvisoErrorKind kind;
  /**
   * HTTP status when `kind` is `AvisoErrorKind_Http`, else `0`.
   */
  uint16_t http_status;
  /**
   * Human-readable message (never null). Credentials are never included;
   * server-supplied error text (such as an HTTP response body) may be.
   */
  const char *message;
  /**
   * Server-supplied request id, or null when unknown.
   */
  const char *request_id;
  /**
   * Trigger label when `kind` is `AvisoErrorKind_Trigger`, else null.
   */
  const char *trigger_kind;
  /**
   * Trigger inner-error label when applicable, else null.
   */
  const char *error_kind;
} AvisoError;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the library version as a static, NUL-terminated string. The pointer
 * is valid for the life of the process and must not be freed.
 */
const char *aviso_version(void);

/**
 * Publishes a notification asynchronously. When it finishes, `on_complete` is
 * called exactly once (normally on a runtime thread) with an owning outcome
 * (the response JSON, or a structured error): free it with
 * `aviso_outcome_free`. The callback must not unwind across the boundary.
 * No-op if `on_complete` is null.
 *
 * # Safety
 *
 * `client` must be a live handle from a successful build. `event_type`,
 * `identifier_json`, and `payload_json`, when non-null, must be NUL-terminated
 * C strings. `ctx` is passed verbatim to `on_complete`.
 */
void aviso_client_notify_async(const AvisoClient *client,
                               const char *event_type,
                               const char *identifier_json,
                               const char *payload_json,
                               void (*on_complete)(void *ctx, AvisoOutcome *outcome),
                               void *ctx);

/**
 * Fetches the full schema catalog asynchronously. When it finishes,
 * `on_complete` is called exactly once (normally on a runtime thread) with an
 * owning outcome (the catalog JSON, or a structured error): free it with
 * `aviso_outcome_free`. The callback must not unwind across the boundary.
 * No-op if `on_complete` is null.
 *
 * # Safety
 *
 * `client` must be a live handle from a successful build. `ctx` is passed
 * verbatim to `on_complete`.
 */
void aviso_client_schema_async(const AvisoClient *client,
                               void (*on_complete)(void *ctx, AvisoOutcome *outcome),
                               void *ctx);

/**
 * Fetches one stream's schema asynchronously. When it finishes, `on_complete`
 * is called exactly once (normally on a runtime thread) with an owning outcome (the
 * schema JSON, or a structured error): free it with `aviso_outcome_free`. The
 * callback must not unwind across the boundary. No-op if `on_complete` is null.
 *
 * # Safety
 *
 * `client` must be a live handle from a successful build. `event_type`, when
 * non-null, must be a NUL-terminated C string. `ctx` is passed verbatim to
 * `on_complete`.
 */
void aviso_client_schema_for_async(const AvisoClient *client,
                                   const char *event_type,
                                   void (*on_complete)(void *ctx, AvisoOutcome *outcome),
                                   void *ctx);

/**
 * Wipes one stream asynchronously (operator-only). When it finishes,
 * `on_complete` is called exactly once (normally on a runtime thread) with an
 * owning outcome (an empty success, or a structured error): free it with
 * `aviso_outcome_free`. The callback must not unwind across the boundary.
 * No-op if `on_complete` is null.
 *
 * # Safety
 *
 * `client` must be a live handle from a successful build. `stream_name`, when
 * non-null, must be a NUL-terminated C string. `ctx` is passed verbatim to
 * `on_complete`.
 */
void aviso_client_wipe_stream_async(const AvisoClient *client,
                                    const char *stream_name,
                                    void (*on_complete)(void *ctx, AvisoOutcome *outcome),
                                    void *ctx);

/**
 * Wipes every stream asynchronously (operator-only). When it finishes,
 * `on_complete` is called exactly once (normally on a runtime thread) with an
 * owning outcome (an empty success, or a structured error): free it with
 * `aviso_outcome_free`. The callback must not unwind across the boundary.
 * No-op if `on_complete` is null.
 *
 * # Safety
 *
 * `client` must be a live handle from a successful build. `ctx` is passed
 * verbatim to `on_complete`.
 */
void aviso_client_wipe_all_async(const AvisoClient *client,
                                 void (*on_complete)(void *ctx, AvisoOutcome *outcome),
                                 void *ctx);

/**
 * Deletes one notification by its `<event_type>@<sequence>` id asynchronously
 * (operator-only). When it finishes, `on_complete` is called exactly once
 * (normally on a runtime thread) with an owning outcome (an empty success, or
 * a structured error): free it with `aviso_outcome_free`. The callback must
 * not unwind across the boundary. No-op if `on_complete` is null.
 *
 * # Safety
 *
 * `client` must be a live handle from a successful build. `notification_id`,
 * when non-null, must be a NUL-terminated C string. `ctx` is passed verbatim
 * to `on_complete`.
 */
void aviso_client_delete_notification_async(const AvisoClient *client,
                                            const char *notification_id,
                                            void (*on_complete)(void *ctx, AvisoOutcome *outcome),
                                            void *ctx);

/**
 * Creates a client builder for `base_url`. Returns a builder handle (null only
 * if an internal panic is trapped); a null or non-UTF-8 `base_url` is
 * remembered and reported at build time. Free an abandoned builder with
 * `aviso_client_builder_free`.
 *
 * # Safety
 *
 * `base_url`, when non-null, must point to a NUL-terminated C string.
 */
AvisoClientBuilder *aviso_client_builder_new(const char *base_url);

/**
 * Creates a client builder from the aviso config file, with a credential
 * found the way the `aviso` binary finds one.
 *
 * Reads `~/.config/aviso/config.yaml`, or the file named in
 * `AVISO_CLIENT_CONFIG_FILE`, for the base URL, timeouts and TLS settings,
 * then searches the environment, the file's `auth:` block and the
 * credentials file for a credential. A missing file sets nothing; a file
 * that exists but cannot be used, or a credential that may not travel to the
 * configured address, is remembered and reported at build time. Setters
 * called afterwards replace what the file said.
 *
 * Returns a builder handle, or null only if an internal panic is trapped.
 */
AvisoClientBuilder *aviso_client_builder_from_file(void);

/**
 * Like `aviso_client_builder_from_file`, reading the file at `path`. The
 * path must exist; a missing file is reported at build time.
 *
 * # Safety
 *
 * `path` must be a NUL-terminated C string.
 */
AvisoClientBuilder *aviso_client_builder_from_file_at(const char *path);

/**
 * Sets or replaces the base URL. After `aviso_client_builder_from_file` this
 * overrides what the file said, or supplies an address the file lacked. A
 * null or non-UTF-8 argument is remembered and reported at build time.
 *
 * # Safety
 *
 * `builder` must be a live builder handle. `base_url`, when non-null, must be
 * a NUL-terminated C string.
 */
void aviso_client_builder_base_url(AvisoClientBuilder *builder, const char *base_url);

/**
 * Builds the client, consuming the builder. On entry the builder is taken and
 * the caller's pointer is set to null (so a later free is a safe no-op), even
 * when the build fails. Returns an outcome carrying the client (retrieve it
 * with `aviso_outcome_take_client`) or a structured error.
 *
 * # Safety
 *
 * `builder` must point to a builder-handle pointer. `*builder`, when non-null,
 * must be a live handle from `aviso_client_builder_new`.
 */
AvisoOutcome *aviso_client_builder_build(AvisoClientBuilder **builder);

/**
 * Frees an abandoned client builder. Builders consumed by
 * `aviso_client_builder_build` are already freed; calling this on the
 * nulled-out pointer is a safe no-op.
 *
 * # Safety
 *
 * `builder`, when non-null, must be a live handle from
 * `aviso_client_builder_new` that was not consumed by a build.
 */
void aviso_client_builder_free(AvisoClientBuilder *builder);

/**
 * Frees a client. A null pointer is a no-op.
 *
 * # Safety
 *
 * `client`, when non-null, must be a live handle and not already freed.
 */
void aviso_client_free(AvisoClient *client);

/**
 * Fetches the schema catalog (`GET /api/v1/schema`) and returns it as a
 * compact-JSON string success value (retrieve it with
 * `aviso_outcome_take_string`), or a structured error.
 *
 * This call blocks. It must not be called from a thread already inside the
 * runtime (for example a watch or async callback); doing so returns an
 * `AvisoErrorKind_InvalidUsage` error.
 *
 * # Safety
 *
 * `client` must be a live handle from a successful build.
 */
AvisoOutcome *aviso_client_schema(const AvisoClient *client);

/**
 * Publishes a notification (`POST /api/v1/notification`) and returns the
 * server's response as a compact-JSON string success value (retrieve it with
 * `aviso_outcome_take_string`), or a structured error.
 *
 * `event_type` is required. `identifier_json`, when non-null, is a JSON object
 * whose values may have any JSON shape; `payload_json`, when non-null, is any
 * JSON value. A null `identifier_json` or `payload_json` means the field is
 * omitted; a non-UTF-8 or otherwise malformed argument is an
 * `AvisoErrorKind_InvalidInput` error.
 *
 * This call blocks. It must not be called from a thread already inside the
 * runtime (for example a watch or async callback); doing so returns an
 * `AvisoErrorKind_InvalidUsage` error.
 *
 * # Safety
 *
 * `client` must be a live handle from a successful build. `event_type`,
 * `identifier_json`, and `payload_json`, when non-null, must be NUL-terminated
 * C strings.
 */
AvisoOutcome *aviso_client_notify(const AvisoClient *client,
                                  const char *event_type,
                                  const char *identifier_json,
                                  const char *payload_json);

/**
 * Publishes many notifications concurrently and returns one result per
 * request, in input order, as a compact-JSON array string success value
 * (retrieve it with `aviso_outcome_take_string`).
 *
 * `notifications_json` is a JSON array; each element is an object with a
 * required string `event_type`, an optional `identifier` object of
 * arbitrary JSON values, and an optional `payload` of any shape. A malformed
 * array or element is an `AvisoErrorKind_InvalidInput` error and nothing is
 * published. `max_concurrency` caps in-flight requests; `0` selects a default.
 *
 * On a valid array the call always succeeds at the ABI level: per-item
 * failures are reported in the array, not as a call error. Each element is
 * `{"index":N,"status":"ok","response":{...}}` or `{"index":N,"status":"error",
 * "error":{"kind":"...","http_status":N,"message":"...","request_id":"..."}}`.
 *
 * This call blocks. It must not be called from a thread already inside the
 * runtime (for example a watch or async callback); doing so returns an
 * `AvisoErrorKind_InvalidUsage` error.
 *
 * # Safety
 *
 * `client` must be a live handle from a successful build. `notifications_json`,
 * when non-null, must be a NUL-terminated C string.
 */
AvisoOutcome *aviso_client_notify_many(const AvisoClient *client,
                                       const char *notifications_json,
                                       uintptr_t max_concurrency);

/**
 * Fetches the schema for one event type (`GET /api/v1/schema/{event_type}`)
 * and returns it as a compact-JSON string success value (retrieve it with
 * `aviso_outcome_take_string`), or a structured error.
 *
 * This call blocks. It must not be called from a thread already inside the
 * runtime (for example a watch or async callback); doing so returns an
 * `AvisoErrorKind_InvalidUsage` error.
 *
 * # Safety
 *
 * `client` must be a live handle from a successful build. `event_type`, when
 * non-null, must be a NUL-terminated C string.
 */
AvisoOutcome *aviso_client_schema_for(const AvisoClient *client, const char *event_type);

/**
 * Wipes every notification for one stream (`DELETE
 * /api/v1/admin/wipe/stream`). Operator-only. Returns an empty success outcome
 * or a structured error.
 *
 * This call blocks. It must not be called from a thread already inside the
 * runtime (for example a watch or async callback); doing so returns an
 * `AvisoErrorKind_InvalidUsage` error.
 *
 * # Safety
 *
 * `client` must be a live handle from a successful build. `stream_name`, when
 * non-null, must be a NUL-terminated C string.
 */
AvisoOutcome *aviso_client_wipe_stream(const AvisoClient *client, const char *stream_name);

/**
 * Wipes every stream (`DELETE /api/v1/admin/wipe/all`). Operator-only. Returns
 * an empty success outcome or a structured error.
 *
 * This call blocks. It must not be called from a thread already inside the
 * runtime (for example a watch or async callback); doing so returns an
 * `AvisoErrorKind_InvalidUsage` error.
 *
 * # Safety
 *
 * `client` must be a live handle from a successful build.
 */
AvisoOutcome *aviso_client_wipe_all(const AvisoClient *client);

/**
 * Deletes a single notification by its `<event_type>@<sequence>` id (`DELETE
 * /api/v1/admin/notification/{id}`). Operator-only. Returns an empty success
 * outcome or a structured error.
 *
 * This call blocks. It must not be called from a thread already inside the
 * runtime (for example a watch or async callback); doing so returns an
 * `AvisoErrorKind_InvalidUsage` error.
 *
 * # Safety
 *
 * `client` must be a live handle from a successful build. `notification_id`,
 * when non-null, must be a NUL-terminated C string.
 */
AvisoOutcome *aviso_client_delete_notification(const AvisoClient *client,
                                               const char *notification_id);

/**
 * Sets HTTP Basic credentials on the builder. A null or non-UTF-8 argument, or
 * a credential-construction failure, is remembered and reported at build time.
 *
 * # Safety
 *
 * `builder` must be a live builder handle from `aviso_client_builder_new`.
 * `username` and `password`, when non-null, must be NUL-terminated C strings.
 */
void aviso_client_builder_basic_auth(AvisoClientBuilder *builder,
                                     const char *username,
                                     const char *password);

/**
 * Sets a Bearer token on the builder. A null, non-UTF-8 or empty token is
 * remembered and reported at build time.
 *
 * This names the credential explicitly, so it is sent to whatever address
 * the builder was given, plain http included. Use
 * `aviso_client_builder_discover_auth` when the token is supplied by the
 * environment or a file rather than by the caller.
 *
 * # Safety
 *
 * `builder` must be a live builder handle from `aviso_client_builder_new`.
 * `token`, when non-null, must be a NUL-terminated C string.
 */
void aviso_client_builder_bearer_auth(AvisoClientBuilder *builder, const char *token);

/**
 * Looks for a credential and uses it if one is found.
 *
 * The search order is the environment, then the `auth:` block of the config
 * file, then the credentials file, which is the same order the `aviso` binary
 * uses. Finding nothing changes nothing: a credential set earlier with
 * `aviso_client_builder_bearer_auth` or `aviso_client_builder_basic_auth`
 * stays, and a builder with none stays anonymous. Finding a source that
 * cannot be used is remembered and reported at build time.
 *
 * A credential found this way is not sent to a plain http address unless it
 * is loopback; that too is reported at build time. When the caller holds the
 * credential, `aviso_client_builder_bearer_auth` or
 * `aviso_client_builder_basic_auth` name it instead, and a named credential
 * goes to whatever address the builder was given.
 *
 * # Safety
 *
 * `builder` must be a live builder handle from `aviso_client_builder_new`.
 */
void aviso_client_builder_discover_auth(AvisoClientBuilder *builder);

/**
 * Creates a client builder with nothing named in code, the way a script on
 * a machine set up for the `aviso` command wants one.
 *
 * The address comes from `AVISO_BASE_URL`, then the config file's
 * `base_url`; the credential from `AVISO_TOKEN` or `AVISO_USERNAME` with
 * `AVISO_PASSWORD`, then the file's `auth:` block, then the credentials
 * file; timeouts and TLS settings from the file. Setters called afterwards
 * replace what was found. With no address anywhere, or a found credential
 * headed for a plain http address that is not loopback, the error is
 * reported at build time. `aviso_client_builder_describe` shows what was
 * chosen and from where.
 *
 * Returns a builder handle, or null only if an internal panic is trapped.
 */
AvisoClientBuilder *aviso_client_builder_from_environment(void);

/**
 * Reports the settings a client built from this builder would use and
 * where each came from, one per line, without building. Nothing in the
 * text is a secret: the credential is described by kind and source, and
 * the address has any `user:password@` removed, so it can be logged or
 * pasted into a ticket as it is.
 *
 * The builder is not consumed. The outcome carries the text; take it with
 * `aviso_outcome_take_string` and free it with `aviso_string_free`. An
 * error remembered by the builder, or a config file that cannot be read,
 * is returned as the outcome's error instead.
 *
 * # Safety
 *
 * `builder` must be a live builder handle.
 */
AvisoOutcome *aviso_client_builder_describe(const AvisoClientBuilder *builder);

/**
 * Returns `true` when the outcome carries no error.
 *
 * # Safety
 *
 * `outcome`, when non-null, must be a live pointer returned by this library
 * and not yet freed. A null pointer is tolerated and returns `false`.
 */
bool aviso_outcome_is_ok(const AvisoOutcome *outcome);

/**
 * Returns a borrowed pointer to the structured error, or null when the outcome
 * is a success. The pointer is valid until the outcome is freed.
 *
 * # Safety
 *
 * `outcome`, when non-null, must be a live pointer returned by this library
 * and not yet freed. A null pointer is tolerated and returns null.
 */
const AvisoError *aviso_outcome_error(const AvisoOutcome *outcome);

/**
 * Removes and returns the outcome's string success value, transferring
 * ownership to the caller, who must free it with `aviso_string_free`.
 * Returns null when the outcome holds no string (an error, an empty success,
 * or a value already taken).
 *
 * # Safety
 *
 * `outcome`, when non-null, must be a live pointer returned by this library
 * and not yet freed. A null pointer is tolerated and returns null.
 */
char *aviso_outcome_take_string(AvisoOutcome *outcome);

/**
 * Removes and returns the outcome's client success value, transferring
 * ownership to the caller, who must free it with `aviso_client_free`. Returns
 * null when the outcome holds no client.
 *
 * # Safety
 *
 * `outcome`, when non-null, must be a live pointer returned by this library
 * and not yet freed. A null pointer is tolerated and returns null.
 */
AvisoClient *aviso_outcome_take_client(AvisoOutcome *outcome);

/**
 * Frees an outcome. Any success value not taken out first is freed with it.
 * A null pointer is a no-op.
 *
 * # Safety
 *
 * `outcome` must be a pointer returned by this library and not already freed.
 */
void aviso_outcome_free(AvisoOutcome *outcome);

/**
 * Frees a string returned by an `..._take_string` accessor. A null pointer is
 * a no-op.
 *
 * # Safety
 *
 * `text` must be a pointer returned by this library's take-string accessors
 * and not already freed.
 */
void aviso_string_free(char *text);

/**
 * Builds an echo trigger (writes each notification as compact JSON to standard
 * output). Free an abandoned trigger with `aviso_trigger_free`.
 */
AvisoTrigger *aviso_trigger_echo(void);

/**
 * Builds a log trigger that appends each notification as compact JSON to the
 * file at `path`. A null or non-UTF-8 `path` is remembered and surfaced when
 * the watch starts.
 *
 * # Safety
 *
 * `path`, when non-null, must be a NUL-terminated C string.
 */
AvisoTrigger *aviso_trigger_log(const char *path);

/**
 * Builds a command trigger that runs `/bin/sh -c <cmd>` per notification. The
 * command trigger is Unix-only: on a non-Unix target this returns a handle
 * carrying an `InvalidUsage` error (surfaced when the watch starts), so the
 * symbol exists on every platform and the ABI stays uniform. A null or
 * non-UTF-8 `cmd` is remembered and surfaced when the watch starts.
 *
 * # Safety
 *
 * `cmd`, when non-null, must be a NUL-terminated C string.
 */
AvisoTrigger *aviso_trigger_command(const char *cmd);

/**
 * Builds a webhook trigger that sends an HTTP request per notification to
 * `url`. A null or non-UTF-8 `url` is remembered and surfaced when the watch
 * starts.
 *
 * # Safety
 *
 * `url`, when non-null, must be a NUL-terminated C string.
 */
AvisoTrigger *aviso_trigger_webhook(const char *url);

/**
 * Builds a Teams trigger that posts an Adaptive Card per notification to the
 * Teams Workflows webhook `url`. A null or non-UTF-8 `url` is remembered and
 * surfaced when the watch starts.
 *
 * # Safety
 *
 * `url`, when non-null, must be a NUL-terminated C string.
 */
AvisoTrigger *aviso_trigger_teams(const char *url);

/**
 * Builds a post trigger that forwards the raw `CloudEvent` envelope as an HTTP
 * POST per notification to `url`. A null or non-UTF-8 `url` is remembered and
 * surfaced when the watch starts.
 *
 * # Safety
 *
 * `url`, when non-null, must be a NUL-terminated C string.
 */
AvisoTrigger *aviso_trigger_post(const char *url);

/**
 * Sets the echo trigger's listener-attribution label. A null or non-UTF-8
 * `label` is remembered and surfaced when the watch starts. Ignored on other
 * trigger kinds.
 *
 * # Safety
 *
 * `trigger` must be a live handle from a trigger factory. `label`, when
 * non-null, must be a NUL-terminated C string.
 */
void aviso_trigger_set_label(AvisoTrigger *trigger, const char *label);

/**
 * Sets the retry count (additional attempts after the first failure).
 *
 * # Safety
 *
 * `trigger` must be a live handle from a trigger factory.
 */
void aviso_trigger_set_retries(AvisoTrigger *trigger, uint32_t retries);

/**
 * Sets whether the trigger is required (a required trigger's terminal failure
 * ends the watch; an optional trigger's failure is logged and the watch
 * continues).
 *
 * # Safety
 *
 * `trigger` must be a live handle from a trigger factory.
 */
void aviso_trigger_set_required(AvisoTrigger *trigger, bool required);

/**
 * Sets a per-trigger timeout in seconds. Meaningful for the command and
 * HTTP-based triggers; ignored on echo and log.
 *
 * # Safety
 *
 * `trigger` must be a live handle from a trigger factory.
 */
void aviso_trigger_set_timeout_secs(AvisoTrigger *trigger, uint64_t timeout_secs);

/**
 * Sets the fail-fast policy on terminal failures. Meaningful for the command
 * and HTTP-based triggers.
 *
 * # Safety
 *
 * `trigger` must be a live handle from a trigger factory.
 */
void aviso_trigger_set_fail_fast(AvisoTrigger *trigger, bool fail_fast);

/**
 * Sets the HTTP method for a webhook trigger from an `AvisoHttpMethod`
 * discriminant. Taken as an integer (not the enum) so an out-of-range value
 * from C is a remembered `InvalidInput` error rather than undefined behaviour;
 * an unknown discriminant is recorded and surfaced when the watch starts.
 * Ignored on other trigger kinds.
 *
 * # Safety
 *
 * `trigger` must be a live handle from a trigger factory.
 */
void aviso_trigger_set_method(AvisoTrigger *trigger, uint32_t method);

/**
 * Adds a request header to a webhook trigger. A null or non-UTF-8 `name` or
 * `value` is remembered and surfaced when the watch starts. Ignored on other
 * trigger kinds.
 *
 * # Safety
 *
 * `trigger` must be a live handle from a trigger factory. `name` and `value`,
 * when non-null, must be NUL-terminated C strings.
 */
void aviso_trigger_set_header(AvisoTrigger *trigger, const char *name, const char *value);

/**
 * Sets the body template for a webhook trigger. A null or non-UTF-8 `body` is
 * remembered and surfaced when the watch starts. Ignored on other trigger
 * kinds.
 *
 * # Safety
 *
 * `trigger` must be a live handle from a trigger factory. `body`, when
 * non-null, must be a NUL-terminated C string.
 */
void aviso_trigger_set_body_template(AvisoTrigger *trigger, const char *body);

/**
 * Adds an environment variable to a command trigger's child process. The
 * command trigger is Unix-only; on a non-Unix target this records an
 * `InvalidUsage` error. A null or non-UTF-8 `key` or `value` is remembered and
 * surfaced when the watch starts. Ignored on other trigger kinds.
 *
 * # Safety
 *
 * `trigger` must be a live handle from a trigger factory. `key` and `value`,
 * when non-null, must be NUL-terminated C strings.
 */
void aviso_trigger_set_env(AvisoTrigger *trigger, const char *key, const char *value);

/**
 * Sets the working directory for a command trigger's child process. The
 * command trigger is Unix-only; on a non-Unix target this records an
 * `InvalidUsage` error. A null or non-UTF-8 `dir` is remembered and surfaced
 * when the watch starts. Ignored on other trigger kinds.
 *
 * # Safety
 *
 * `trigger` must be a live handle from a trigger factory. `dir`, when
 * non-null, must be a NUL-terminated C string.
 */
void aviso_trigger_set_working_dir(AvisoTrigger *trigger, const char *dir);

/**
 * Frees an abandoned trigger. Triggers consumed by
 * `aviso_watch_request_add_trigger` are already freed; calling this on the
 * nulled-out pointer is a safe no-op.
 *
 * # Safety
 *
 * `trigger`, when non-null, must be a live handle from a trigger factory that
 * was not consumed by an add.
 */
void aviso_trigger_free(AvisoTrigger *trigger);

/**
 * Creates a live-watch request for `event_type`. Returns a handle (null only
 * if an internal panic is trapped); a null or non-UTF-8 `event_type` is
 * remembered and surfaced when the watch starts. Free an abandoned request
 * with `aviso_watch_request_free`.
 *
 * # Safety
 *
 * `event_type`, when non-null, must be a NUL-terminated C string.
 */
AvisoWatchRequest *aviso_watch_request_new(const char *event_type);

/**
 * Sets the identifier filter from a JSON object string (a null argument clears
 * it). A non-UTF-8 or non-object argument is remembered and surfaced when the
 * watch starts.
 *
 * # Safety
 *
 * `request` must be a live handle from `aviso_watch_request_new`.
 * `filter_json`, when non-null, must be a NUL-terminated C string.
 */
void aviso_watch_request_set_filter_json(AvisoWatchRequest *request, const char *filter_json);

/**
 * Resumes a live watch after the given sequence (the watch replays everything
 * after `sequence`, then goes live).
 *
 * # Safety
 *
 * `request` must be a live handle from `aviso_watch_request_new`.
 */
void aviso_watch_request_watch_from_sequence(AvisoWatchRequest *request, uint64_t sequence);

/**
 * Resumes a live watch from the given date string (server-defined format),
 * replaying from that point and then going live.
 *
 * # Safety
 *
 * `request` must be a live handle from `aviso_watch_request_new`. `date`, when
 * non-null, must be a NUL-terminated C string.
 */
void aviso_watch_request_watch_from_date(AvisoWatchRequest *request, const char *date);

/**
 * Switches the request to replay-only from the given sequence: it replays
 * everything after `sequence` and then ends, without going live.
 *
 * # Safety
 *
 * `request` must be a live handle from `aviso_watch_request_new`.
 */
void aviso_watch_request_replay_from_sequence(AvisoWatchRequest *request, uint64_t sequence);

/**
 * Switches the request to replay-only from the given date string: it replays
 * from that point and then ends, without going live.
 *
 * # Safety
 *
 * `request` must be a live handle from `aviso_watch_request_new`. `date`, when
 * non-null, must be a NUL-terminated C string.
 */
void aviso_watch_request_replay_from_date(AvisoWatchRequest *request, const char *date);

/**
 * Attaches a trigger to the request, consuming the trigger handle: on entry
 * the trigger is taken and the caller's pointer is nulled (so a later free is
 * a safe no-op). A trigger built from a bad argument is remembered on the
 * request and surfaced through the watch's `on_end` when it starts.
 *
 * # Safety
 *
 * `request` must be a live handle from `aviso_watch_request_new`. `trigger`
 * must point to a trigger-handle pointer; `*trigger`, when non-null, must be a
 * live handle from a trigger factory.
 */
void aviso_watch_request_add_trigger(AvisoWatchRequest *request, AvisoTrigger **trigger);

/**
 * Frees an abandoned watch request. Requests consumed by `aviso_client_watch`
 * are already freed; calling this on the nulled-out pointer is a safe no-op.
 *
 * # Safety
 *
 * `request`, when non-null, must be a live handle from
 * `aviso_watch_request_new` that was not consumed by a watch start.
 */
void aviso_watch_request_free(AvisoWatchRequest *request);

/**
 * Returns the notification's event type. The pointer is valid only for the
 * duration of the `on_notification` call.
 *
 * # Safety
 *
 * `notification` must be the pointer passed to the current `on_notification`
 * call.
 */
const char *aviso_notification_event_type(const AvisoNotification *notification);

/**
 * Returns the notification's per-stream sequence number.
 *
 * # Safety
 *
 * `notification` must be the pointer passed to the current `on_notification`
 * call. A null pointer returns `0`.
 */
uint64_t aviso_notification_sequence(const AvisoNotification *notification);

/**
 * Returns the notification's identifier as a compact-JSON object string. The
 * pointer is valid only for the duration of the `on_notification` call.
 *
 * # Safety
 *
 * `notification` must be the pointer passed to the current `on_notification`
 * call.
 */
const char *aviso_notification_identifier_json(const AvisoNotification *notification);

/**
 * Returns the notification's payload as a compact-JSON string (`null` when the
 * payload was absent). The pointer is valid only for the duration of the
 * `on_notification` call.
 *
 * # Safety
 *
 * `notification` must be the pointer passed to the current `on_notification`
 * call.
 */
const char *aviso_notification_payload_json(const AvisoNotification *notification);

/**
 * Starts a watch, consuming the request. The watch runs on the global runtime
 * and returns at once; `on_notification` fires per notification (returning
 * `false` requests a graceful stop) and `on_end` fires exactly once when the
 * stream ends or fails, taking ownership of the outcome. Every watch error,
 * at start or mid-stream, arrives through `on_end`.
 *
 * Returns null when `client`, the request, `on_notification`, or `on_end` is
 * null (no watch starts), or if an internal panic is trapped. On entry the
 * request is taken and the caller's pointer is nulled, so a later free is a
 * safe no-op.
 *
 * The callbacks run on a watch (runtime) thread, so they must be thread-safe,
 * must not unwind across the boundary, and must not make blocking aviso calls.
 *
 * # Safety
 *
 * `client` must be a live handle from a successful build. `request` must point
 * to a request-handle pointer; `*request`, when non-null, must be a live
 * handle from `aviso_watch_request_new`. `ctx` is passed verbatim to the
 * callbacks and must stay valid until `on_end` has returned.
 */
AvisoWatch *aviso_client_watch(const AvisoClient *client,
                               AvisoWatchRequest **request,
                               bool (*on_notification)(void *ctx,
                                                       const AvisoNotification *notification),
                               void (*on_end)(void *ctx, AvisoOutcome *outcome),
                               void *ctx);

/**
 * Requests a graceful stop. Nonblocking, idempotent, and safe to call from a
 * callback. A callback already running finishes; no new callback starts after
 * the stop is observed. `on_end` still fires once. A null pointer is a no-op.
 *
 * # Safety
 *
 * `watch`, when non-null, must be a live handle from `aviso_client_watch`.
 */
void aviso_watch_stop(const AvisoWatch *watch);

/**
 * Blocks until the watch has fully ended and its `on_end` has returned.
 * Returns an empty success outcome, or an `AvisoErrorKind_InvalidUsage` error
 * when called from inside a callback (a runtime thread). Idempotent: a second
 * call after completion returns success at once.
 *
 * # Safety
 *
 * `watch` must be a live handle from `aviso_client_watch`.
 */
AvisoOutcome *aviso_watch_wait(const AvisoWatch *watch);

/**
 * Frees a watch handle. Signals a stop first so a still-running task winds
 * down rather than running forever, then detaches it. Call `aviso_watch_wait`
 * before freeing if `on_end` may touch state you are about to release; freeing
 * alone does not wait for `on_end`. A null pointer is a no-op.
 *
 * # Safety
 *
 * `watch`, when non-null, must be a live handle from `aviso_client_watch` that
 * was not already freed.
 */
void aviso_watch_free(AvisoWatch *watch);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
