#pragma once

/* Generated by cbindgen from crates/aviso-ffi. Do not edit by hand. Regenerate with `cargo run -p aviso-ffi --features gen-header --bin gen-header`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Discriminates an `AvisoError`.
 *
 * The first ten kinds mirror the core `ClientError`; the rest are conditions
 * the ABI itself reports: bad arguments, misuse, internal faults, a caught
 * Rust panic, and an unmapped (future) core variant. The discriminants are
 * fixed for ABI stability.
 */
typedef enum {
  /**
   * Network-level failure (connect, TLS, DNS, partial read).
   */
  AvisoErrorKind_Transport = 0,
  /**
   * Server returned a non-success HTTP status.
   */
  AvisoErrorKind_Http = 1,
  /**
   * Authentication setup or credential resolution failed.
   */
  AvisoErrorKind_Auth = 2,
  /**
   * A response body could not be decoded.
   */
  AvisoErrorKind_Decode = 3,
  /**
   * A `CloudEvent` envelope carried a malformed event id.
   */
  AvisoErrorKind_MalformedEvent = 4,
  /**
   * A gap was detected in a watch stream.
   */
  AvisoErrorKind_HistoryGap = 5,
  /**
   * A fatal wire-protocol condition was observed on a watch stream.
   */
  AvisoErrorKind_StreamProtocol = 6,
  /**
   * Configuration-time error (invalid source, missing field).
   */
  AvisoErrorKind_Config = 7,
  /**
   * A persistent state-store operation failed.
   */
  AvisoErrorKind_StateStore = 8,
  /**
   * A required trigger failed after all retries.
   */
  AvisoErrorKind_Trigger = 9,
  /**
   * An argument was null, not UTF-8, or otherwise malformed.
   */
  AvisoErrorKind_InvalidInput = 10,
  /**
   * The call was used incorrectly (for example, a blocking call from a
   * runtime or callback thread).
   */
  AvisoErrorKind_InvalidUsage = 11,
  /**
   * An internal invariant was violated.
   */
  AvisoErrorKind_Internal = 12,
  /**
   * A Rust panic was caught at the boundary.
   */
  AvisoErrorKind_Panic = 13,
  /**
   * An unmapped core error variant (the core enum grew).
   */
  AvisoErrorKind_Unknown = 14,
} AvisoErrorKind;

/**
 * Opaque client handle. Wraps the core client (cheap to clone, shares the
 * connection pool and auth state).
 */
typedef struct AvisoClient AvisoClient;

/**
 * Opaque client-builder handle. Setters mutate it in place; the first error
 * (a bad argument or an auth-construction failure) is remembered and surfaced
 * at `aviso_client_builder_build`.
 */
typedef struct AvisoClientBuilder AvisoClientBuilder;

/**
 * A read-only view of one notification, valid only for the `on_notification`
 * call it is passed to. The `identifier` and `payload` are pre-serialized to
 * compact JSON; the accessors return borrowed pointers into this view.
 */
typedef struct AvisoNotification AvisoNotification;

/**
 * Result of a fallible C ABI call. Opaque to C; always freed with
 * `aviso_outcome_free`.
 */
typedef struct AvisoOutcome AvisoOutcome;

/**
 * Opaque handle to a running watch. Stop it with `aviso_watch_stop`, block for
 * its completion with `aviso_watch_wait`, and release it with
 * `aviso_watch_free`.
 */
typedef struct AvisoWatch AvisoWatch;

/**
 * Opaque builder for a watch request. Setters mutate it in place; the first
 * bad argument is remembered and surfaced through `on_end` when the watch
 * starts. Consumed by `aviso_client_watch` (which nulls the caller's pointer)
 * or freed with `aviso_watch_request_free`.
 */
typedef struct AvisoWatchRequest AvisoWatchRequest;

/**
 * C-visible error detail. The `const char*` fields borrow from the owning
 * `AvisoOutcome` and are valid until it is freed. A pointer
 * is null when the field does not apply (`request_id` when unknown,
 * `trigger_kind` / `error_kind` unless `kind` is `AvisoErrorKind_Trigger`).
 */
typedef struct {
  /**
   * The error kind.
   */
  AvisoErrorKind kind;
  /**
   * HTTP status when `kind` is `AvisoErrorKind_Http`, else `0`.
   */
  uint16_t http_status;
  /**
   * Human-readable message (never null). Credentials are never included;
   * server-supplied error text (such as an HTTP response body) may be.
   */
  const char *message;
  /**
   * Server-supplied request id, or null when unknown.
   */
  const char *request_id;
  /**
   * Trigger label when `kind` is `AvisoErrorKind_Trigger`, else null.
   */
  const char *trigger_kind;
  /**
   * Trigger inner-error label when applicable, else null.
   */
  const char *error_kind;
} AvisoError;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the library version as a static, NUL-terminated string. The pointer
 * is valid for the life of the process and must not be freed.
 */
const char *aviso_version(void);

/**
 * Creates a client builder for `base_url`. Returns a builder handle (null only
 * if an internal panic is trapped); a null or non-UTF-8 `base_url` is
 * remembered and reported at build time. Free an abandoned builder with
 * `aviso_client_builder_free`.
 *
 * # Safety
 *
 * `base_url`, when non-null, must point to a NUL-terminated C string.
 */
AvisoClientBuilder *aviso_client_builder_new(const char *base_url);

/**
 * Sets HTTP Basic credentials on the builder. A null or non-UTF-8 argument, or
 * a credential-construction failure, is remembered and reported at build time.
 *
 * # Safety
 *
 * `builder` must be a live builder handle from `aviso_client_builder_new`.
 * `username` and `password`, when non-null, must be NUL-terminated C strings.
 */
void aviso_client_builder_basic_auth(AvisoClientBuilder *builder,
                                     const char *username,
                                     const char *password);

/**
 * Builds the client, consuming the builder. On entry the builder is taken and
 * the caller's pointer is set to null (so a later free is a safe no-op), even
 * when the build fails. Returns an outcome carrying the client (retrieve it
 * with `aviso_outcome_take_client`) or a structured error.
 *
 * # Safety
 *
 * `builder` must point to a builder-handle pointer. `*builder`, when non-null,
 * must be a live handle from `aviso_client_builder_new`.
 */
AvisoOutcome *aviso_client_builder_build(AvisoClientBuilder **builder);

/**
 * Frees an abandoned client builder. Builders consumed by
 * `aviso_client_builder_build` are already freed; calling this on the
 * nulled-out pointer is a safe no-op.
 *
 * # Safety
 *
 * `builder`, when non-null, must be a live handle from
 * `aviso_client_builder_new` that was not consumed by a build.
 */
void aviso_client_builder_free(AvisoClientBuilder *builder);

/**
 * Frees a client. A null pointer is a no-op.
 *
 * # Safety
 *
 * `client`, when non-null, must be a live handle and not already freed.
 */
void aviso_client_free(AvisoClient *client);

/**
 * Fetches the schema catalog (`GET /api/v1/schema`) and returns it as a
 * compact-JSON string success value (retrieve it with
 * `aviso_outcome_take_string`), or a structured error.
 *
 * This call blocks. It must not be called from a thread already inside the
 * runtime (for example a watch or async callback); doing so returns an
 * `AvisoErrorKind_InvalidUsage` error.
 *
 * # Safety
 *
 * `client` must be a live handle from a successful build.
 */
AvisoOutcome *aviso_client_schema(const AvisoClient *client);

/**
 * Publishes a notification (`POST /api/v1/notification`) and returns the
 * server's response as a compact-JSON string success value (retrieve it with
 * `aviso_outcome_take_string`), or a structured error.
 *
 * `event_type` is required. `identifier_json`, when non-null, is a JSON object
 * of string-to-string identifier pairs; `payload_json`, when non-null, is any
 * JSON value. A null `identifier_json` or `payload_json` means the field is
 * omitted; a non-UTF-8 or otherwise malformed argument is an
 * `AvisoErrorKind_InvalidInput` error.
 *
 * This call blocks. It must not be called from a thread already inside the
 * runtime (for example a watch or async callback); doing so returns an
 * `AvisoErrorKind_InvalidUsage` error.
 *
 * # Safety
 *
 * `client` must be a live handle from a successful build. `event_type`,
 * `identifier_json`, and `payload_json`, when non-null, must be NUL-terminated
 * C strings.
 */
AvisoOutcome *aviso_client_notify(const AvisoClient *client,
                                  const char *event_type,
                                  const char *identifier_json,
                                  const char *payload_json);

/**
 * Fetches the schema for one event type (`GET /api/v1/schema/{event_type}`)
 * and returns it as a compact-JSON string success value (retrieve it with
 * `aviso_outcome_take_string`), or a structured error.
 *
 * This call blocks. It must not be called from a thread already inside the
 * runtime (for example a watch or async callback); doing so returns an
 * `AvisoErrorKind_InvalidUsage` error.
 *
 * # Safety
 *
 * `client` must be a live handle from a successful build. `event_type`, when
 * non-null, must be a NUL-terminated C string.
 */
AvisoOutcome *aviso_client_schema_for(const AvisoClient *client, const char *event_type);

/**
 * Wipes every notification for one stream (`DELETE
 * /api/v1/admin/wipe/stream`). Operator-only. Returns an empty success outcome
 * or a structured error.
 *
 * This call blocks. It must not be called from a thread already inside the
 * runtime (for example a watch or async callback); doing so returns an
 * `AvisoErrorKind_InvalidUsage` error.
 *
 * # Safety
 *
 * `client` must be a live handle from a successful build. `stream_name`, when
 * non-null, must be a NUL-terminated C string.
 */
AvisoOutcome *aviso_client_wipe_stream(const AvisoClient *client, const char *stream_name);

/**
 * Wipes every stream (`DELETE /api/v1/admin/wipe/all`). Operator-only. Returns
 * an empty success outcome or a structured error.
 *
 * This call blocks. It must not be called from a thread already inside the
 * runtime (for example a watch or async callback); doing so returns an
 * `AvisoErrorKind_InvalidUsage` error.
 *
 * # Safety
 *
 * `client` must be a live handle from a successful build.
 */
AvisoOutcome *aviso_client_wipe_all(const AvisoClient *client);

/**
 * Deletes a single notification by its `<event_type>@<sequence>` id (`DELETE
 * /api/v1/admin/notification/{id}`). Operator-only. Returns an empty success
 * outcome or a structured error.
 *
 * This call blocks. It must not be called from a thread already inside the
 * runtime (for example a watch or async callback); doing so returns an
 * `AvisoErrorKind_InvalidUsage` error.
 *
 * # Safety
 *
 * `client` must be a live handle from a successful build. `notification_id`,
 * when non-null, must be a NUL-terminated C string.
 */
AvisoOutcome *aviso_client_delete_notification(const AvisoClient *client,
                                               const char *notification_id);

/**
 * Returns `true` when the outcome carries no error.
 *
 * # Safety
 *
 * `outcome`, when non-null, must be a live pointer returned by this library
 * and not yet freed. A null pointer is tolerated and returns `false`.
 */
bool aviso_outcome_is_ok(const AvisoOutcome *outcome);

/**
 * Returns a borrowed pointer to the structured error, or null when the outcome
 * is a success. The pointer is valid until the outcome is freed.
 *
 * # Safety
 *
 * `outcome`, when non-null, must be a live pointer returned by this library
 * and not yet freed. A null pointer is tolerated and returns null.
 */
const AvisoError *aviso_outcome_error(const AvisoOutcome *outcome);

/**
 * Removes and returns the outcome's string success value, transferring
 * ownership to the caller, who must free it with `aviso_string_free`.
 * Returns null when the outcome holds no string (an error, an empty success,
 * or a value already taken).
 *
 * # Safety
 *
 * `outcome`, when non-null, must be a live pointer returned by this library
 * and not yet freed. A null pointer is tolerated and returns null.
 */
char *aviso_outcome_take_string(AvisoOutcome *outcome);

/**
 * Removes and returns the outcome's client success value, transferring
 * ownership to the caller, who must free it with `aviso_client_free`. Returns
 * null when the outcome holds no client.
 *
 * # Safety
 *
 * `outcome`, when non-null, must be a live pointer returned by this library
 * and not yet freed. A null pointer is tolerated and returns null.
 */
AvisoClient *aviso_outcome_take_client(AvisoOutcome *outcome);

/**
 * Frees an outcome. Any success value not taken out first is freed with it.
 * A null pointer is a no-op.
 *
 * # Safety
 *
 * `outcome` must be a pointer returned by this library and not already freed.
 */
void aviso_outcome_free(AvisoOutcome *outcome);

/**
 * Frees a string returned by an `..._take_string` accessor. A null pointer is
 * a no-op.
 *
 * # Safety
 *
 * `text` must be a pointer returned by this library's take-string accessors
 * and not already freed.
 */
void aviso_string_free(char *text);

/**
 * Creates a live-watch request for `event_type`. Returns a handle (null only
 * if an internal panic is trapped); a null or non-UTF-8 `event_type` is
 * remembered and surfaced when the watch starts. Free an abandoned request
 * with `aviso_watch_request_free`.
 *
 * # Safety
 *
 * `event_type`, when non-null, must be a NUL-terminated C string.
 */
AvisoWatchRequest *aviso_watch_request_new(const char *event_type);

/**
 * Sets the identifier filter from a JSON object string (a null argument clears
 * it). A non-UTF-8 or non-object argument is remembered and surfaced when the
 * watch starts.
 *
 * # Safety
 *
 * `request` must be a live handle from `aviso_watch_request_new`.
 * `filter_json`, when non-null, must be a NUL-terminated C string.
 */
void aviso_watch_request_set_filter_json(AvisoWatchRequest *request, const char *filter_json);

/**
 * Resumes a live watch after the given sequence (the watch replays everything
 * after `sequence`, then goes live).
 *
 * # Safety
 *
 * `request` must be a live handle from `aviso_watch_request_new`.
 */
void aviso_watch_request_watch_from_sequence(AvisoWatchRequest *request, uint64_t sequence);

/**
 * Resumes a live watch from the given date string (server-defined format),
 * replaying from that point and then going live.
 *
 * # Safety
 *
 * `request` must be a live handle from `aviso_watch_request_new`. `date`, when
 * non-null, must be a NUL-terminated C string.
 */
void aviso_watch_request_watch_from_date(AvisoWatchRequest *request, const char *date);

/**
 * Switches the request to replay-only from the given sequence: it replays
 * everything after `sequence` and then ends, without going live.
 *
 * # Safety
 *
 * `request` must be a live handle from `aviso_watch_request_new`.
 */
void aviso_watch_request_replay_from_sequence(AvisoWatchRequest *request, uint64_t sequence);

/**
 * Switches the request to replay-only from the given date string: it replays
 * from that point and then ends, without going live.
 *
 * # Safety
 *
 * `request` must be a live handle from `aviso_watch_request_new`. `date`, when
 * non-null, must be a NUL-terminated C string.
 */
void aviso_watch_request_replay_from_date(AvisoWatchRequest *request, const char *date);

/**
 * Frees an abandoned watch request. Requests consumed by `aviso_client_watch`
 * are already freed; calling this on the nulled-out pointer is a safe no-op.
 *
 * # Safety
 *
 * `request`, when non-null, must be a live handle from
 * `aviso_watch_request_new` that was not consumed by a watch start.
 */
void aviso_watch_request_free(AvisoWatchRequest *request);

/**
 * Returns the notification's event type. The pointer is valid only for the
 * duration of the `on_notification` call.
 *
 * # Safety
 *
 * `notification` must be the pointer passed to the current `on_notification`
 * call.
 */
const char *aviso_notification_event_type(const AvisoNotification *notification);

/**
 * Returns the notification's per-stream sequence number.
 *
 * # Safety
 *
 * `notification` must be the pointer passed to the current `on_notification`
 * call. A null pointer returns `0`.
 */
uint64_t aviso_notification_sequence(const AvisoNotification *notification);

/**
 * Returns the notification's identifier as a compact-JSON object string. The
 * pointer is valid only for the duration of the `on_notification` call.
 *
 * # Safety
 *
 * `notification` must be the pointer passed to the current `on_notification`
 * call.
 */
const char *aviso_notification_identifier_json(const AvisoNotification *notification);

/**
 * Returns the notification's payload as a compact-JSON string (`null` when the
 * payload was absent). The pointer is valid only for the duration of the
 * `on_notification` call.
 *
 * # Safety
 *
 * `notification` must be the pointer passed to the current `on_notification`
 * call.
 */
const char *aviso_notification_payload_json(const AvisoNotification *notification);

/**
 * Starts a watch, consuming the request. The watch runs on the global runtime
 * and returns at once; `on_notification` fires per notification (returning
 * `false` requests a graceful stop) and `on_end` fires exactly once when the
 * stream ends or fails, taking ownership of the outcome. Every watch error,
 * at start or mid-stream, arrives through `on_end`.
 *
 * Returns null when `client`, the request, `on_notification`, or `on_end` is
 * null (no watch starts), or if an internal panic is trapped. On entry the
 * request is taken and the caller's pointer is nulled, so a later free is a
 * safe no-op.
 *
 * The callbacks run on a watch (runtime) thread, so they must be thread-safe,
 * must not unwind across the boundary, and must not make blocking aviso calls.
 *
 * # Safety
 *
 * `client` must be a live handle from a successful build. `request` must point
 * to a request-handle pointer; `*request`, when non-null, must be a live
 * handle from `aviso_watch_request_new`. `ctx` is passed verbatim to the
 * callbacks and must stay valid until `on_end` has returned.
 */
AvisoWatch *aviso_client_watch(const AvisoClient *client,
                               AvisoWatchRequest **request,
                               bool (*on_notification)(void *ctx,
                                                       const AvisoNotification *notification),
                               void (*on_end)(void *ctx, AvisoOutcome *outcome),
                               void *ctx);

/**
 * Requests a graceful stop. Nonblocking, idempotent, and safe to call from a
 * callback. A callback already running finishes; no new callback starts after
 * the stop is observed. `on_end` still fires once. A null pointer is a no-op.
 *
 * # Safety
 *
 * `watch`, when non-null, must be a live handle from `aviso_client_watch`.
 */
void aviso_watch_stop(const AvisoWatch *watch);

/**
 * Blocks until the watch has fully ended and its `on_end` has returned.
 * Returns an empty success outcome, or an `AvisoErrorKind_InvalidUsage` error
 * when called from inside a callback (a runtime thread). Idempotent: a second
 * call after completion returns success at once.
 *
 * # Safety
 *
 * `watch` must be a live handle from `aviso_client_watch`.
 */
AvisoOutcome *aviso_watch_wait(const AvisoWatch *watch);

/**
 * Frees a watch handle. Signals a stop first so a still-running task winds
 * down rather than running forever, then detaches it. Call `aviso_watch_wait`
 * before freeing if `on_end` may touch state you are about to release; freeing
 * alone does not wait for `on_end`. A null pointer is a no-op.
 *
 * # Safety
 *
 * `watch`, when non-null, must be a live handle from `aviso_client_watch` that
 * was not already freed.
 */
void aviso_watch_free(AvisoWatch *watch);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
